export const GET_RECORD_REQUESTED = 'GET_RECORD_REQUESTED' as const;
export const GET_RECORD_SUCCEEDED = 'GET_RECORD_SUCCEEDED' as const;
export const GET_RECORD_FAILED = 'GET_RECORD_FAILED' as const;

export const PATCH_RECORD_REQUESTED = 'PATCH_RECORD_REQUESTED' as const;
export const PATCH_RECORD_SUCCEEDED = 'PATCH_RECORD_SUCCEEDED' as const;
export const PATCH_RECORD_FAILED = 'PATCH_RECORD_FAILED' as const;

export const DELETE_RECORD_REQUESTED = 'DELETE_RECORD_REQUESTED' as const;
export const DELETE_RECORD_SUCCEEDED = 'DELETE_RECORD_SUCCEEDED' as const;
export const DELETE_RECORD_FAILED = 'DELETE_RECORD_FAILED' as const;

export const CREATE_RECORD_REQUESTED = 'CREATE_RECORD_REQUESTED' as const;
export const CREATE_RECORD_SUCCEEDED = 'CREATE_RECORD_SUCCEEDED' as const;
export const CREATE_RECORD_FAILED = 'CREATE_RECORD_FAILED' as const;

export const RESET_RECORD = 'RESET_RECORD' as const;
