export const PATCH_RECORD_REQUESTED = 'PATCH_RECORD_REQUESTED' as const;
export const PATCH_RECORD_SUCCEEDED = 'PATCH_RECORD_SUCCEEDED' as const;
export const PATCH_RECORD_FAILED = 'PATCH_RECORD_FAILED' as const;
