export const PATCH_REPRESENTATIVE_REQUESTED = 'PATCH_REPRESENTATIVE_REQUESTED' as const;
export const PATCH_REPRESENTATIVE_SUCCEEDED = 'PATCH_REPRESENTATIVE_SUCCEEDED' as const;
export const PATCH_REPRESENTATIVE_FAILED = 'PATCH_REPRESENTATIVE_FAILED' as const;
