export const FETCH_ALL_REPRESENTATIVES_REQUESTED = 'FETCH_ALL_REPRESENTATIVES_REQUESTED' as const;
export const FETCH_ALL_REPRESENTATIVES_SUCCEEDED = 'FETCH_ALL_REPRESENTATIVES_SUCCEEDED' as const;
export const FETCH_ALL_REPRESENTATIVES_FAILED = 'FETCH_ALL_REPRESENTATIVES_FAILED' as const;

export const PATCH_REPRESENTATIVE_REQUESTED = 'PATCH_REPRESENTATIVE_REQUESTED' as const;
export const PATCH_REPRESENTATIVE_SUCCEEDED = 'PATCH_REPRESENTATIVE_SUCCEEDED' as const;
export const PATCH_REPRESENTATIVE_FAILED = 'PATCH_REPRESENTATIVE_FAILED' as const;
