export const FETCH_ORGANIZATION_REQUESTED =
  'FETCH_ORGANIZATION_REQUESTED' as const;
export const FETCH_ORGANIZATION_SUCCEEDED =
  'FETCH_ORGANIZATION_SUCCEEDED' as const;
export const FETCH_ORGANIZATION_FAILED = 'FETCH_ORGANIZATION_FAILED' as const;
