export const FETCH_ALL_RECORDS_REQUESTED = 'FETCH_ALL_RECORDS_REQUESTED' as const;
export const FETCH_ALL_RECORDS_SUCCEEDED = 'FETCH_ALL_RECORDS_SUCCEEDED' as const;
export const FETCH_ALL_RECORDS_FAILED = 'FETCH_ALL_RECORDS_FAILED' as const;
