name: Deploy to demo

on:
  repository_dispatch:
    types: [deploy-demo]

jobs:
  deploy-demo:
    name: Deploy latest production image to demo environment
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Apply Helm template
        run: |
          helm repo add fdk https://informasjonsforvaltning.github.io/helm-chart/
          helm fetch --untar --untardir ./helm fdk/records-of-processing-activities-gui
          helm template --set DOCKER_IMAGE_NAME="eu.gcr.io/digdir-fdk-infra/records-of-processing-activities-gui:${{ github.event.client_payload.sha }}" -f ./helm/records-of-processing-activities-gui/values/demo.yaml ./helm/records-of-processing-activities-gui/ > ./kubectlapply.yaml
          chmod o+w ./kubectlapply.yaml
          cat kubectlapply.yaml

      - name: Get kubeconfig file from GKE
        uses: machine-learning-apps/gke-kubeconfig@master
        with:
          application_credentials: ${{ secrets.DIGDIR_FDK_DEV_AUTODEPLOY }}
          project_id: digdir-fdk-dev
          location_zone: europe-north1-a
          cluster_name: digdir-fdk-dev

      - name: Deploy to demo
        uses: docker://bitnami/kubectl:latest
        env:
          KUBECONFIG: '/github/workspace/.kube/config'
        with:
          args: "apply -f ./kubectlapply.yaml --force"

      - name: Notify slack
        uses: 8398a7/action-slack@v3
        with:
          mention: 'channel'
          if_mention: failure
          status: ${{ job.status }}
          author_name: 'Application: records-of-processing-activities-gui | Environment: demo'
          fields: commit,author,workflow
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
